### ISSUE TITLE
Error/CTD

### ISSUE THREAD

**Issue by ShneekeyTheLost** [Skarsnik/Bizhawk-nwa-tool#1]
On Linux Mint 20.3, when I run the tool it appears to work, however during AP the connection continually times out, and eventually CTD's BizHawk. Not sure where the error logs are to provide. This was also in conjunction with SNI rather than QUSB, but I doubt that would make a difference. I can compile QUSB if you need me to try compatibility with that.

**Comment by Skarsnik** [comment]
I am not sure if this work on Linux. It will not work with SNI since it does not have NWA support.

Sadly there is no log file. The only thing can you check is in the view menu -> show log

**Comment by ShneekeyTheLost** [comment]
I thought the whole point was to bypass the buggy LUA implementation in the Linux distro of BizHawk, at least that's the thread it was linked in. 

QUSB is no longer supported by AP, so nevermind.
